name: weather_app
description: A mobile weather application using OpenWeatherMap API

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^10.0.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  glassmorphism: ^3.0.0
  animations: ^2.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21